### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by junedgar** [natanielruiz/deep-head-pose#17]
I tried to train the model with:
```python train_hopenet.py --gpu=1 --num_epochs=30 --batch_size=16 --lr=0.00001 --dataset=Pose_300W_LP_random_ds --data_dir=../dataSet/300W_LP --filename_list=../filePath --output_string=headPose --alpha=1```
with the error:
```/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
CUDA error after cudaEventDestroy in future dtor: device-side assert triggeredTraceback (most recent call last):
  File "train_hopenet.py", line 177, in <module>
    loss_reg_yaw = reg_criterion(yaw_predicted, label_yaw_cont)```

Did somebody encounter this problem?
@natanielruiz

**Comment by junedgar** [comment]
I solved the problem by clean the data,  only use the angle in ±99. Thank you for your great work @natanielruiz!

**Comment by tangbohu** [comment]
@junedgar  Dear Junedgar, could you share me the filename_list via email(tangbohutbh@gmail.com). Thanks!
